# meta information for the course
title: Constrained Root Solvers
description: Learning constrained root solvers in Julia
template:
  repo: juliant-template
  name: learn-constrained-root-solvers
  description: Learning constrained root solvers in Julia

# create a new issue after cloning the repository
before:
  - type: createIssue
    title: Learning ConstrainedRootSolvers.jl
    body: 00-new-issue.md

steps:
  # 1. install the package to the project
  - title: Install ConstrainedRootSolvers
    description: Initialize the project and add ConstrainedRootSolvers
    event: pull_request
    link: '{{ repoUrl }}'
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        operator: ===
        right: add ConstrainedRootSolvers
        else:
          - type: respond
            with: 01-fail.md
      - type: respond
        with: 01-succeed.md
  # 2. enable the branch protection
  - title: Enable Branch Protection
    description: Add branch protection rule to main
    event: commit_comment
    link: '{{ repoUrl }}'
    actions:
      - type: respond
        with: 02-info.md
  # 3. define and export a few functions to test
